name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'matter-labs/era-test-node'
          ref: 'ad-dev'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev clang

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run Test Node
        run: | 
          nohup cargo run --release run
        
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      
      - name: Install dependencies
        run: yarn install
        
      # This is required separately from yarn test because it generates the typechain definitions
      - name: Compile
        run: yarn compile

      - name: Run tests
        run: yarn test --network zkSyncTestNode
